src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/resources/application.properties
src/test/java/io/fabric8/che/starter/controller/CheServerControllerTest.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java
src/test/java/io/fabric8/che/starter/openshift/OpenShiftTest.java

Changing Openshift endpoint address for k8s tests

---

cico_run_tests.sh
src/main/java/io/fabric8/che/starter/client/CheRestClient.java
src/main/java/io/fabric8/che/starter/client/CheRestEndpoints.java
src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/controller/StackController.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java

Defining API contract

---

README.md

Usefull to debug Che when running on OpenShift

Added instructions to start Che in debug mode

---

src/main/java/io/fabric8/che/starter/openshift/OpenShiftClientWrapper.java
src/test/java/io/fabric8/che/starter/client/StackClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

Enabling Stack and some Workspace tests. Removing startPodIfNeeded check

---

deploy_che_on_minishift.sh
src/main/resources/application-test.properties

Adding script for che server deployment based on fabric8 online template

---

README.md
deploy_che_on_minishift.sh

Updating script for deployment Che to Minishift

---

src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java

If something goes wrong and Che server does not start, REST call fails

Fixed timeout for starting Che server

---

src/main/java/io/fabric8/che/starter/util/ProjectHelper.java
src/test/java/io/fabric8/che/starter/util/ProjectHelperTest.java

Fixing project's name obtaining logic

---

src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakEndpoint.java

Adding correct Keycloak oso endpoint

---

src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/openshift/OpenShiftClientWrapper.java
src/test/java/io/fabric8/che/starter/openshift/RouteTest.java

Fixed closing of OpenShift client once it is not needed anymore

---

src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/controller/StackController.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java

added also description to authorization params in swagger for both kind of calls (Keycloak, OpenShift)

Implement OpenShift auth header on endpoints for Che server calls

---

Dockerfile
src/main/java/io/fabric8/che/starter/openshift/OpenShiftClientWrapper.java

Setting valid certificate to Openshift client

---

src/main/resources/templates/workspace_template.json

Wait until https://github.com/eclipse/che/pull/4472 is merged, then merge this one.

Removed ssh agent from workspace definition

---

Dockerfile

related to the issue described by @ibuziuk here https://github.com/redhat-developer/che-starter/pull/55#issuecomment-287892847
ping @ibuziuk

Set ownership and permissions for the CHE_STARTER_HOME dir

---

src/main/java/io/fabric8/che/starter/client/TokenClient.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/exception/GitHubOAthTokenException.java
src/main/java/io/fabric8/che/starter/exception/GlobalExceptionHandler.java
src/test/java/io/fabric8/che/starter/client/GitHubTokenClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

Adding GitHub token test

---

src/main/java/io/fabric8/che/starter/client/StackClient.java
src/main/java/io/fabric8/che/starter/model/StackProjectMapping.java
src/main/java/io/fabric8/che/starter/template/CheServerTemplate.java
src/main/java/io/fabric8/che/starter/template/ProjectTemplate.java
src/main/java/io/fabric8/che/starter/template/TokenTemplate.java
src/main/java/io/fabric8/che/starter/template/WorkspaceTemplate.java

https://github.com/redhat-developer/che-starter/issues/70

Che #70 - Adding API for getting project type by stack id

---

src/main/java/io/fabric8/che/starter/template/CheServerTemplate.java
src/test/java/io/fabric8/che/starter/controller/CheServerControllerTest.java

this will spare us of ~400 lines of useless output

Removed template output from info log, it polluted output too much

---

pom.xml
src/main/resources/checkstyle.xml

Initial contribution of checkstyle rules

---

pom.xml
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakClient.java
src/test/java/io/fabric8/che/starter/TestBase.java
src/test/java/io/fabric8/che/starter/controller/StackControllerTest.java

+ minor fix of NPE in keycloak client

More integration tests for endpoints with keycloak, updated vertx server

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/model/request/WorkspaceCreateParams.java
src/test/java/io/fabric8/che/starter/TestBase.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

Simplified Create workspace API, removed unused params

---

pom.xml
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/model/request/WorkspaceCreateParams.java
src/main/java/io/fabric8/che/starter/util/WorkspaceHelper.java
src/test/java/io/fabric8/che/starter/TestBase.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

Extended Create WS params for description

---

src/main/java/io/fabric8/che/starter/openshift/CheServerRoute.java

che #100 - Adding support for route protocol detection

---

src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakClient.java

Switching default Keycloak endpoints to htpps

---

src/main/java/io/fabric8/che/starter/openshift/CheServerRoute.java

Adding tls check for protocol verification

---

src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceConfig.java
src/main/java/io/fabric8/che/starter/util/WorkspaceHelper.java

tested locally on minishift, created 2 distinct WS with different repos, then tried to get first, then second, then non-existing

Filtering workspaces based on repo works with POJO instead of description

---

src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/model/project/Project.java

Fixed project type passed to WS Master

---

src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakClient.java

Adding logs for Keycloak endpoints

---

src/main/java/io/fabric8/che/starter/client/WorkspacePreferencesClient.java
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/util/ProjectHelper.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

che #74 Adding support for setting GitHub user info automatically

---

src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/model/project/Project.java

che #113 Fixing project type

---

src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/model/project/Project.java

che #113 adding 'type' property to  Project DTO

---

src/main/java/io/fabric8/che/starter/client/CheRestEndpoints.java
src/main/java/io/fabric8/che/starter/client/GitHubClient.java
src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/exception/WorkspaceNotFound.java
src/main/java/io/fabric8/che/starter/model/Token.java
src/main/java/io/fabric8/che/starter/model/project/ProjectLink.java
src/main/java/io/fabric8/che/starter/model/project/Source.java
src/main/java/io/fabric8/che/starter/model/request/WorkspaceCreateParams.java
src/main/java/io/fabric8/che/starter/model/stack/Stack.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceCommand.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceConfig.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceEnvironment.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceEnvironments.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceMachine.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceMachineAttribute.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceRecipe.java
src/main/java/io/fabric8/che/starter/util/WorkspaceHelper.java
src/main/resources/checkstyle.xml
src/test/java/io/fabric8/che/starter/TestBase.java
src/test/java/io/fabric8/che/starter/controller/StackControllerTest.java
src/test/java/io/fabric8/che/starter/controller/VertxServer.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

che #131 Code formatting should not contain tab characters

---

src/main/java/io/fabric8/che/starter/model/stack/StackProjectMapping.java

Adding mapping for CentOS based stacks

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/resources/application-local.properties

Signed-off-by: Shane Bryzak <sbryzak@redhat.com>

ISSUE-128, wait for workspace to stop before starting new workspace

---

openshift-template/che-starter.app.yaml

we are not getting values, since the rendered template does not consider the configmap at all

indent up for the vars to actually work

---

openshift-template/che-starter.app.yaml

This adds health checks for OpenShift based on new `/status` endpoint

Add health checks

---

openshift-template/che-starter.app.yaml

Please, let me know if you don't think these limits are reasonable.

Add resource requests/limits

---

src/main/java/io/fabric8/che/starter/client/GitHubClient.java
src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/client/StackClient.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/client/WorkspacePreferencesClient.java
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakClient.java
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakInterceptor.java
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakRestTemplate.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/test/java/io/fabric8/che/starter/client/GitHubTokenClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

che #51: Sending Keycloak token with every request to che server

---

pom.xml
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakTokenValidator.java
src/main/java/io/fabric8/che/starter/controller/StackController.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/exception/GlobalExceptionHandler.java
src/main/java/io/fabric8/che/starter/exception/InvalidKeycloakTokenFormatException.java
src/test/java/io/fabric8/che/starter/TestBase.java
src/test/java/io/fabric8/che/starter/controller/StackControllerTest.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

Adding validator for Keycloak Token

---

src/main/java/io/fabric8/che/starter/model/WorspacePreferences.java

Setting git properties correctly

---

.gitignore
openshift-template/README.md
openshift-template/che-starter.config.yaml

Updating instructions for Minishift deployment

---

src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakClient.java

che #161: Adding support for obtaining OSO token from ENV var

---

src/main/java/io/fabric8/che/starter/client/CheRestEndpoints.java
src/main/java/io/fabric8/che/starter/client/WorkspacePreferencesClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/model/WorkspacePreferences.java
src/test/java/io/fabric8/che/starter/client/GitHubTokenClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspacePreferencesClientTest.java

che #168: Setting GitHub token during workspace startup

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakTokenValidator.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java

Cosmetic fixes: formatting, unused vars & imports

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

Adding some logs in 'waitWhileWorkspaceStop' method

---

src/test/java/io/fabric8/che/starter/TestBase.java
src/test/java/io/fabric8/che/starter/controller/WorkspaceControllerTest.java

che #178: Enabling disabled workspace tests

---

src/test/java/io/fabric8/che/starter/util/UrlHelperTest.java

Improving URL Helper test

---

README.md

Removing obsolete CI job from documentation

---

README.md

Adding CI build status icon

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java

Signed-off-by: Ilya Buziuk <ilyabuziuk@gmail.com>

Do not wait if there is no PODs to stop

---

src/main/java/io/fabric8/che/starter/Application.java
src/main/java/io/fabric8/che/starter/client/CheServerClient.java
src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/model/response/CheServerInfo.java
src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java

Endpoint for getting che-server state `isRunning`
First part of https://github.com/redhat-developer/che-starter/issues/163

che #163 - Adding GET '/server' for providing che server state info

---

src/main/resources/application-test.properties
src/test/java/io/fabric8/che/starter/client/GitHubTokenClientTest.java
src/test/java/io/fabric8/che/starter/client/StackClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspacePreferencesClientTest.java

che #185: Executing integration tests against free-int cluster

---

src/main/java/io/fabric8/che/starter/client/CheRestEndpoints.java
src/main/java/io/fabric8/che/starter/client/GitHubClient.java

More details in https://github.com/redhat-developer/rh-che/pull/98

CHE-272: Adding support of new GitHub access token API

---

src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java

(potential fix of 503 errors which might be coupled with HAProxy configuration reloading)
see - https://github.com/redhat-developer/rh-che/issues/115
see - https://youtu.be/xgLY3HCshZc

rh-che-115: Waiting 3 seconds after che-server deployment is available

---

README.md

more cosmetics in README.md

---

README.md

Updating preview route information

---

src/main/java/io/fabric8/che/starter/client/github/GitHubClient.java
src/main/resources/application-test.properties
src/test/java/io/fabric8/che/starter/client/StackClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspacePreferencesClientTest.java
src/test/java/io/fabric8/che/starter/client/github/GitHubTokenClientTest.java
src/test/java/io/fabric8/che/starter/client/keycloak/KeycloakTokenValidatorTest.java
src/test/java/io/fabric8/che/starter/openshift/OpenShiftTest.java

Temporary moving all integration tests to prod cluster

---

src/main/java/io/fabric8/che/starter/client/ProjectClient.java

Project client refactoring

---

src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/model/project/Project.java

rh-che-228: Removing projectType property during workspace creation

---

src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java

Increasing thread sleep to 15 seconds in 'waitHAProxyConfigChange'

---

src/main/java/io/fabric8/che/starter/client/CheRestEndpoints.java
src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java
src/main/java/io/fabric8/che/starter/util/ProjectHelper.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

issue https://github.com/redhat-developer/che-starter/issues/214

che #214 Skip importing a project but save it to ws-config during workspace creation

---

src/main/java/io/fabric8/che/starter/client/CheServerClient.java
src/main/java/io/fabric8/che/starter/client/WorkspacePreferencesClient.java
src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java
src/main/java/io/fabric8/che/starter/openshift/CheServerRouteChecker.java
src/test/java/io/fabric8/che/starter/client/WorkspacePreferencesClientTest.java

openshift.io-579 Adding hot fixes for 3.6 endpoint delay issue to /server API

---

src/main/java/io/fabric8/che/starter/client/CheServerClient.java
src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java
src/main/java/io/fabric8/che/starter/openshift/CheServerRouteChecker.java

openshift.io-579 Improving hot fixes for 3.6 endpoint delay issue to /server API

---

src/main/java/io/fabric8/che/starter/openshift/CheDeploymentConfig.java

Increasing timeout to 60 seconds

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/util/WorkspaceHelper.java
src/main/resources/logback-spring.xml
src/test/java/io/fabric8/che/starter/util/WorkspaceHelperTest.java

openshift.io #446 workspace name should have codebase info (project name) with randomly generated postfix

---

src/main/resources/application-test.properties

Running integration tests against free-int cluster

---

src/main/java/io/fabric8/che/starter/openshift/OpenShiftClientWrapper.java
src/main/resources/application.properties

Adding 'ibuziuk-che' to multi-tenant namespaces. Updating multi-tenant che-server URL

---

pom.xml
src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakTokenParser.java
src/main/java/io/fabric8/che/starter/model/stack/StackProjectMapping.java
src/test/java/io/fabric8/che/starter/client/StackClientTest.java
src/test/java/io/fabric8/che/starter/client/keycloak/KeycloakTokenParserTest.java

Adding getSessionState API for KeycloakTokenParser

---

src/main/java/io/fabric8/che/starter/multi/tenant/MultiTenantToggle.java

Adding 'MultiTenantToggle' component which encapsulates Unleash API

---

openshift-template/che-starter.app.yaml
openshift-template/che-starter.config.yaml

Adding MULTI_TENANT_CHE_SERVER_URL env var to the OpenShift template

---

openshift-template/che-starter.app.yaml
openshift-template/che-starter.config.yaml

che #248 Adding 'update tenant endpoint' to openshift template / cm

---

src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java

che #251: Setting commiter info not only for workspace creation, but also for starting existing

---

src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

Enabling 'createAndDelete' workspace test

---

src/test/java/io/fabric8/che/starter/client/StackClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/client/WorkspacePreferencesClientTest.java
src/test/java/io/fabric8/che/starter/client/github/GitHubTokenClientTest.java

Obtaining osio token from env_var for integration tests

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

More tests for workspaces

---

pom.xml

Adding jacoco plugin report

---

README.md
cico_build_deploy.sh
cico_run_tests.sh
src/main/resources/application-test.properties
src/test/java/io/fabric8/che/starter/client/github/GitHubTokenClientTest.java
src/test/java/io/fabric8/che/starter/client/github/GitHubTokenProviderTest.java

Running che-starter integration tests against prod-preview using keycloak token from 'che_functional_tests_credentials_wrapper'

Running che-starter integration tests against prod-preview using keycloak token from 'che_functional_tests_credentials_wrapper'

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java
src/test/java/io/fabric8/che/starter/util/WorkspaceLegacyFormatAdapterTest.java

Adding workspace start workspace

---

src/main/java/io/fabric8/che/starter/util/WorkspaceComparator.java
src/main/java/io/fabric8/che/starter/util/WorkspaceLegacyFormatAdapter.java
src/test/java/io/fabric8/che/starter/util/WorkspaceLegacyFormatAdapterTest.java

Fixing assert errors

---

src/main/resources/application-test.properties

Running [test] in this PR shows readiness of che6 support in che-starter  master branch

[WIP] Switching integration tests to che6

---

src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceMachine.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceMachineServers.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceMachineV6.java

Fixes https://github.com/redhat-developer/rh-che/issues/582

rh-che-582: Adding support of che 6 version of stacks with installers and servers

---

src/test/java/io/fabric8/che/starter/client/StackClientTest.java

Signed-off-by: Radim Hopp <rhopp@redhat.com>

Add ITest for agents/installers present in Stack to StackClientTest

---

src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/toggle/Che6Toggle.java

https://github.com/redhat-developer/rh-che/issues/583

rh-che-583: Adding support of unleash che 6 toggle

---

src/main/java/io/fabric8/che/starter/client/ProjectClient.java
src/main/java/io/fabric8/che/starter/client/StackClient.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/client/WorkspacePreferencesClient.java
src/main/java/io/fabric8/che/starter/client/github/GitHubClient.java
src/main/java/io/fabric8/che/starter/toggle/Che6Toggle.java
src/main/java/io/fabric8/che/starter/util/CheServerUrlProvider.java

rh-che 583: Adding support of che 6 che server

---

src/main/java/io/fabric8/che/starter/che6/migration/Che6MigrationMap.java
src/main/java/io/fabric8/che/starter/che6/migration/Che6Migrator.java
src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/test/java/io/fabric8/che/starter/che6/migration/Che6MigratorTest.java

Adding async support of che 6 migration in che-starter

---

src/main/java/io/fabric8/che/starter/che6/migration/Che6Migrator.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/model/workspace/WorkspaceStatus.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

Stopping all workspaces before starting workspace migration to che 6

---

src/main/java/io/fabric8/che/starter/che6/migration/Che6Migrator.java
src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/util/CheServerUrlProvider.java
src/test/java/io/fabric8/che/starter/client/WorkspaceClientTest.java

Stopping che 5 workspaces. Adding delay while getting che server state

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java

Stopping che 5 workspaces

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java

Adding logs with info of how long does an async startup execution take

---

cico_build_deploy.sh

debug cico rhel target var

---

cico_build_deploy.sh

Reverts redhat-developer/che-starter#294

Revert "debug cico rhel target var"

---

README.md
cico_build_deploy.sh

Reverts redhat-developer/che-starter#293

Revert "trigger build"

---

src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/model/server/CheServerInfo.java
src/main/java/io/fabric8/che/starter/oso/ClusterCapacityTracker.java
src/main/java/io/fabric8/che/starter/util/CheServerHelper.java
src/test/java/io/fabric8/che/starter/util/CheServerHelperTest.java

osio issue https://github.com/openshiftio/openshift.io/issues/3320

osio #3320: Adding new property for tracking oso cluster capacity while obtaining Che info

---

src/main/java/io/fabric8/che/starter/client/keycloak/KeycloakInterceptor.java
src/main/java/io/fabric8/che/starter/exception/GlobalExceptionHandler.java
src/main/java/io/fabric8/che/starter/exception/NamespaceNotFoundException.java
src/main/java/io/fabric8/che/starter/oso/ClusterCapacityTracker.java
src/main/java/io/fabric8/che/starter/oso/user/services/model/Attributes.java
src/main/java/io/fabric8/che/starter/oso/user/services/model/Data.java
src/main/java/io/fabric8/che/starter/oso/user/services/model/Namespace.java
src/main/java/io/fabric8/che/starter/oso/user/services/model/UserServices.java
src/test/java/io/fabric8/che/starter/oso/ClusterCapacityTrackerTest.java

osio issue - https://github.com/openshiftio/openshift.io/issues/3320

osio-3320: Retrieving capacity flag from user services api

---

src/main/java/io/fabric8/che/starter/oso/ClusterCapacityTracker.java
src/test/java/io/fabric8/che/starter/oso/ClusterCapacityTrackerTest.java

Emulating cluster full on prod-preview

---

openshift-template/che-starter.app.yaml
openshift-template/che-starter.config.yaml
src/main/java/io/fabric8/che/starter/oso/ClusterCapacityTracker.java
src/test/java/io/fabric8/che/starter/oso/ClusterCapacityTrackerTest.java

Adding cm entry for OSIO_API_BASE_URL

---

src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java
src/main/java/io/fabric8/che/starter/util/CheServerUrlProvider.java
src/main/resources/application-test.properties

Adding 'osio_spaceId' attribute during workspace creation that would be used by woopra and for OSD support

---

src/main/java/io/fabric8/che/starter/client/StackClient.java
src/main/java/io/fabric8/che/starter/util/WorkspaceHelper.java

Fixing lint issue and removing unnecessary nesting:
squid:s3655: Optional value should only be accessed after calling isPresent()
https://next.sonarqube.com/sonarqube/coding_rules?open=squid%3AS3655&rule_key=squid%3AS3655

Fix squid s3655

---

src/main/java/io/fabric8/che/starter/client/WorkspacePreferencesClient.java
src/main/java/io/fabric8/che/starter/client/github/GitHubClient.java
src/main/java/io/fabric8/che/starter/model/project/Project.java
src/main/java/io/fabric8/che/starter/model/project/Source.java

Minor - fixing squid:S2293
https://next.sonarqube.com/sonarqube/coding_rules?open=squid%3AS2293&q=S2293

Fix squid s2293

---

src/main/java/io/fabric8/che/starter/controller/CheServerController.java
src/main/java/io/fabric8/che/starter/controller/StackController.java
src/main/java/io/fabric8/che/starter/controller/WorkspaceController.java

Making masterURL and namespace fields as optional
Fixes https://github.com/redhat-developer/che-starter/issues/290

290 remove unused mandatory parameters
